CREATE TABLE military (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    srcNo VARCHAR(255) NULL,
    personalNo VARCHAR(255) NULL,
    cadetTrainingNo VARCHAR(255) NULL,
    outOfReason VARCHAR(255) NULL,
    servedArmies VARCHAR(255) NULL,
    caseAndPunishment VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE inheritance (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    inheriNo VARCHAR(255) NULL,
    inheriName VARCHAR(255) NULL,
    inheriRelation VARCHAR(255) NULL,
    inheriAddress VARCHAR(255) NULL,
    inheriRemark VARCHAR(255) NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE children (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    childNo VARCHAR(255) NULL,
    childName VARCHAR(255) NULL,
    childDob DATE NULL,
    childAge VARCHAR(255) NULL,
    childOccupation VARCHAR(255) NULL,
    childAddress VARCHAR(255) NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE medals (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    medalNo VARCHAR(255) NULL,
    medalName VARCHAR(255) NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE crimes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    crimeNo VARCHAR(255) NULL,
    crimeName VARCHAR(255) NULL,
    punishment VARCHAR(255) NULL,
    crimeDate DATE NULL,
    crimeRemark VARCHAR(255) NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE services (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    servedNo VARCHAR(255) NULL,
    servedRank VARCHAR(255) NULL,
    servedPlace VARCHAR(255) NULL,
    servedPeriodFrom DATE NULL,
    servedPeriodTo DATE NULL,
    servedRemark VARCHAR(255) NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE trainingInter (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    traningInterNo VARCHAR(255) NULL,
    traningInterName VARCHAR(255) NULL,
    traningInterPeriodFrom DATE NULL,
    traningInterPeriodTo DATE NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

CREATE TABLE trainingOuter (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    personnel_id BIGINT UNSIGNED NOT NULL,
    traningOuterNo VARCHAR(255) NULL,
    traningOuterName VARCHAR(255) NULL,
    traningOuterPeriodFrom DATE NULL,
    traningOuterPeriodTo DATE NULL,
    FOREIGN KEY (personnel_id) REFERENCES personnel_data(id) ON DELETE CASCADE
);

ALTER TABLE military ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE inheritance ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE children ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE medals ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE crimes ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE services ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE trainingInter ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE trainingOuter ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;





